/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentationRouteImport } from './routes/_authenticated/documentation'
import { Route as AuthenticatedFinderRouteImport } from './routes/_authenticated/finder'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedVerificationHistoryRouteImport } from './routes/_authenticated/verification-history'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings.system'
import { Route as ApiPublicExtensionImportRouteImport } from './routes/api/public/extension/import'
import { Route as ApiPublicExtensionStatusRouteImport } from './routes/api/public/extension/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentationRoute =
  AuthenticatedDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinderRoute = AuthenticatedFinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationHistoryRoute =
  AuthenticatedVerificationHistoryRouteImport.update({
    id: '/verification-history',
    path: '/verification-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicExtensionImportRoute =
  ApiPublicExtensionImportRouteImport.update({
    id: '/api/public/extension/import',
    path: '/api/public/extension/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionStatusRoute =
  ApiPublicExtensionStatusRouteImport.update({
    id: '/api/public/extension/status',
    path: '/api/public/extension/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentation': typeof AuthenticatedDocumentationRoute
  '/finder': typeof AuthenticatedFinderRoute
  '/import': typeof AuthenticatedImportRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/verification-history': typeof AuthenticatedVerificationHistoryRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/extension/import': typeof ApiPublicExtensionImportRoute
  '/api/public/extension/status': typeof ApiPublicExtensionStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentation': typeof AuthenticatedDocumentationRoute
  '/finder': typeof AuthenticatedFinderRoute
  '/import': typeof AuthenticatedImportRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/verification-history': typeof AuthenticatedVerificationHistoryRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/extension/import': typeof ApiPublicExtensionImportRoute
  '/api/public/extension/status': typeof ApiPublicExtensionStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentation': typeof AuthenticatedDocumentationRoute
  '/_authenticated/finder': typeof AuthenticatedFinderRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/verification-history': typeof AuthenticatedVerificationHistoryRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/extension/import': typeof ApiPublicExtensionImportRoute
  '/api/public/extension/status': typeof ApiPublicExtensionStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/documentation'
    | '/finder'
    | '/import'
    | '/jobs'
    | '/verification'
    | '/verification-history'
    | '/leads/$id'
    | '/settings/system'
    | '/leads/'
    | '/settings/'
    | '/api/public/extension/import'
    | '/api/public/extension/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/documentation'
    | '/finder'
    | '/import'
    | '/jobs'
    | '/verification'
    | '/verification-history'
    | '/leads/$id'
    | '/settings/system'
    | '/leads'
    | '/settings'
    | '/api/public/extension/import'
    | '/api/public/extension/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentation'
    | '/_authenticated/finder'
    | '/_authenticated/import'
    | '/_authenticated/jobs'
    | '/_authenticated/verification'
    | '/_authenticated/verification-history'
    | '/_authenticated/leads/$id'
    | '/_authenticated/settings/system'
    | '/_authenticated/leads/'
    | '/_authenticated/settings/'
    | '/api/public/extension/import'
    | '/api/public/extension/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicExtensionImportRoute: typeof ApiPublicExtensionImportRoute
  ApiPublicExtensionStatusRoute: typeof ApiPublicExtensionStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentation': {
      id: '/_authenticated/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AuthenticatedDocumentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finder': {
      id: '/_authenticated/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof AuthenticatedFinderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification-history': {
      id: '/_authenticated/verification-history'
      path: '/verification-history'
      fullPath: '/verification-history'
      preLoaderRoute: typeof AuthenticatedVerificationHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/extension/import': {
      id: '/api/public/extension/import'
      path: '/api/public/extension/import'
      fullPath: '/api/public/extension/import'
      preLoaderRoute: typeof ApiPublicExtensionImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/status': {
      id: '/api/public/extension/status'
      path: '/api/public/extension/status'
      fullPath: '/api/public/extension/status'
      preLoaderRoute: typeof ApiPublicExtensionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentationRoute: typeof AuthenticatedDocumentationRoute
  AuthenticatedFinderRoute: typeof AuthenticatedFinderRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedVerificationHistoryRoute: typeof AuthenticatedVerificationHistoryRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentationRoute: AuthenticatedDocumentationRoute,
  AuthenticatedFinderRoute: AuthenticatedFinderRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedVerificationHistoryRoute: AuthenticatedVerificationHistoryRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicExtensionImportRoute: ApiPublicExtensionImportRoute,
  ApiPublicExtensionStatusRoute: ApiPublicExtensionStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
