/**
 * Pluggable Lead Source architecture.
 *
 * Add a new source by implementing LeadSource and registering it below.
 * Nothing in the UI or database is coupled to a specific provider.
 */
import type { LeadSearchRequest, ProviderDescriptor, RawLead } from "@/lib/domain-types";
import { ProviderNotConfiguredError, ProviderUnavailableError } from "./runtime.server";
import {
  SELF_HOSTED_GMAPS_ID,
  isConfigured as gmapsConfigured,
  searchSelfHostedGoogleMaps,
} from "./self-hosted-google-maps.server";

export interface LeadSource {
  id: string;
  name: string;
  description: string;
  capabilities: string[];
  estimatedCostPerUnit?: number | null;
  configurationHint?: string;
  isConfigured(): boolean;
  search(request: LeadSearchRequest): Promise<RawLead[]>;
}

/**
 * Self-hosted open-source Google Maps discovery.
 *
 * The scraper (gosom/google-maps-scraper, MIT) runs as a separate service you
 * deploy yourself; this adapter only calls its HTTP API server-side.
 */
import { getRuntimeConfig } from "@/lib/config/runtime-config.server";

const selfHostedGoogleMaps: LeadSource = {
  id: SELF_HOSTED_GMAPS_ID,
  name: "Google Maps — Server Scraper (Render)",
  description:
    "Queries your own self-hosted google-maps-scraper service for publicly listed business data.",
  capabilities: [
    "business search",
    "location filter",
    "category filter",
    "public phone",
    "rating & reviews",
  ],
  // Self-hosted: no per-result vendor fee, only your own infrastructure cost.
  estimatedCostPerUnit: 0,
  configurationHint:
    "Deploy the scraper container, then add the GMAPS_SCRAPER_URL secret (plus GMAPS_SCRAPER_API_KEY if your deployment requires one).",
  isConfigured() {
    return gmapsConfigured();
  },
  search: searchSelfHostedGoogleMaps,
};

/**
 * Google Maps Browser Discovery, performed by the "Sales Intel Maps Connector"
 * Chrome extension in the user's own browser. Discovery never runs server-side
 * for this source: the extension posts results to /api/public/extension/import.
 */
const chromeExtensionSource: LeadSource = {
  id: "chrome-extension",
  name: "Google Maps — Chrome Extension (Beta)",
  description:
    "Runs Google Maps discovery locally in your Chrome browser via the Sales Intel Maps Connector extension. No hosted scraper required.",
  capabilities: [
    "business search",
    "runs in your browser",
    "public phone",
    "rating & reviews",
    "no server scraper",
  ],
  estimatedCostPerUnit: 0,
  configurationHint:
    "Install the Sales Intel Maps Connector extension and connect it from Settings → Browser Extension.",
  isConfigured() {
    return true;
  },
  async search() {
    throw new ProviderUnavailableError(
      "Google Maps Browser Discovery runs in the Chrome extension, not on the server. Open Google Maps and start discovery from the extension popup.",
    );
  },
};

/**
 * Demo source. Returns clearly-labelled sample records so the rest of the
 * application can be exercised before a real provider is connected.
 * Records are marked as demo data and are never presented as real businesses.
 */
const demoSource: LeadSource = {
  id: "demo",
  name: "DEMO — Sample Data",
  description:
    "Generates clearly-labelled sample records for testing the app. Not real business data.",
  capabilities: ["testing only"],
  estimatedCostPerUnit: 0,
  isConfigured() {
    return true;
  },
  async search(request) {
    const location = request.location ?? extractLocation(request.query) ?? "Sample City";
    const category = request.industry ?? extractCategory(request.query) ?? "Business";
    const count = Math.min(request.limit ?? 12, 25);
    return Array.from({ length: count }, (_, i) => {
      const n = i + 1;
      const slug = `${category}-${location}-${n}`.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      const hasWebsite = n % 4 !== 0;
      const hasEmail = n % 3 !== 0;
      const hasPhone = n % 5 !== 0;
      return {
        company_name: `[DEMO] ${titleCase(category)} ${n} — ${titleCase(location)}`,
        website: hasWebsite ? `https://${slug}.example.com` : null,
        domain: hasWebsite ? `${slug}.example.com` : null,
        category: titleCase(category),
        description: "Sample record generated by the demo lead source.",
        address: `${n} Example Street`,
        city: titleCase(location),
        region: null,
        country: null,
        postal_code: null,
        phone: hasPhone ? `+44 20 7000 ${String(1000 + n).slice(0, 4)}` : null,
        email: hasEmail ? `info@${slug}.example.com` : null,
        rating: 3 + (n % 20) / 10,
        review_count: 10 * n,
        business_type: titleCase(category),
        opening_status: null,
        social_urls: {},
        attributes: { demo: true },
        source_url: `https://example.com/listings/${slug}`,
      } satisfies RawLead;
    }).filter((lead) => {
      if (request.requireWebsite && !lead.website) return false;
      if (request.requireEmail && !lead.email) return false;
      if (request.requirePhone && !lead.phone) return false;
      return true;
    });
  },
};

function titleCase(value: string) {
  return value.replace(/\b\w/g, (c) => c.toUpperCase());
}
function extractLocation(query: string) {
  const match = /\bin\s+(.+)$/i.exec(query.trim());
  return match?.[1]?.trim() ?? null;
}
function extractCategory(query: string) {
  return query.split(/\bin\b/i)[0]?.trim() || null;
}

// Order matters: the first configured production source is the UI default.
const SOURCES: LeadSource[] = [selfHostedGoogleMaps, chromeExtensionSource, demoSource];

export function listLeadSources(): ProviderDescriptor[] {
  return SOURCES.map((source) => ({
    id: source.id,
    name: source.name,
    kind: "lead_source" as const,
    description: source.description,
    configured: source.isConfigured(),
    configurationHint: source.configurationHint,
    capabilities: source.capabilities,
    estimatedCostPerUnit: source.estimatedCostPerUnit ?? null,
  }));
}

export function getLeadSource(id: string): LeadSource {
  const source = SOURCES.find((s) => s.id === id);
  if (!source) throw new ProviderNotConfiguredError(`Lead source "${id}"`, "Unknown source.");
  return source;
}
